### ISSUE TITLE
node server.js gives syntax error when running

### ISSUE THREAD

**Issue by crichmond** [sintaxi/nhl#5]
SyntaxError: Setter must have exactly one formal parameter.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\nhl-api-master\node_modules\jsdom\lib\jsdom\level2\core.js:1:94)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by renelikestacos** [comment]
Still does the same thing. Nobody checks this issues?

SyntaxError: Setter must have exactly one formal parameter.
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/nhl-api/node_modules/jsdom/lib/jsdom/level2/core.js:1:130)

**Comment by jrnxf** [comment]
Getting the same problem. Any updates?

**Comment by sintaxi** [comment]
This project was built as a demo several years ago. It scrapes the old nhl website before the site change. The architecture should be sound so it shouldn't be difficult to fix up but the DOM parsing and the url to the NHL website will have to be updated.
